'use client';

import React, { useEffect, useState } from 'react';
import { PORTFOLIO_CONFIG, LiveUpdate } from '@/config/portfolio';
import { useLanguage } from './LanguageSelector';
import { Radio, ExternalLink, RefreshCw } from 'lucide-react';

export const LiveNewsFeed: React.FC<{ items?: LiveUpdate[] }> = ({ items }) => {
  const { t } = useLanguage();
  const [updates, setUpdates] = useState<LiveUpdate[]>(items || PORTFOLIO_CONFIG.liveUpdates);
  const [isRefreshing, setIsRefreshing] = useState(false);

  useEffect(() => {
    if (items) return;

    // Fetch dynamic live updates JSON file generated by sync-linkedin.js
    fetch('/data/live-updates.json')
      .then((res) => {
        if (res.ok) return res.json();
        throw new Error('Failed to fetch live updates');
      })
      .then((data: LiveUpdate[]) => {
        if (Array.isArray(data) && data.length > 0) {
          setUpdates(data);
        }
      })
      .catch((err) => {
        console.log('Using default portfolio config live updates fallback.', err);
      });
  }, [items]);

  const handleRefresh = () => {
    setIsRefreshing(true);
    fetch('/data/live-updates.json?t=' + Date.now())
      .then((res) => res.json())
      .then((data: LiveUpdate[]) => {
        if (Array.isArray(data) && data.length > 0) {
          setUpdates(data);
        }
      })
      .finally(() => setTimeout(() => setIsRefreshing(false), 800));
  };

  return (
    <section className="py-12 bg-[#07080a] border-t border-[#1e2436] relative">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        
        {/* News Ticker Container */}
        <div className="bg-[#0e1017] rounded-xl border border-[#00f0ff]/30 p-5 font-mono text-xs hud-border">
          
          <div className="flex items-center justify-between border-b border-[#1e2436] pb-3 mb-4">
            <div className="flex items-center gap-2 text-white font-bold">
              <Radio className="w-4 h-4 text-[#00ff66] animate-pulse" />
              <span>{t.liveUpdates.title}</span>
            </div>
            
            <div className="flex items-center gap-3">
              <button
                onClick={handleRefresh}
                className="text-[#8b95ad] hover:text-[#00f0ff] transition-colors p-1"
                title="Sincronizar Feed de Notícias"
              >
                <RefreshCw className={`w-3.5 h-3.5 ${isRefreshing ? 'animate-spin text-[#00f0ff]' : ''}`} />
              </button>
              <span className="text-[10px] text-[#00f0ff] uppercase bg-[#00f0ff]/10 px-2 py-0.5 rounded border border-[#00f0ff]/30 font-bold">
                {t.liveUpdates.badgeLabel}
              </span>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            {updates.map((item) => (
              <div
                key={item.id}
                className="bg-[#131622] p-4 rounded border border-[#1e2436] hover:border-[#00f0ff]/40 transition-all flex flex-col justify-between"
              >
                <div>
                  <div className="flex items-center justify-between text-[10px] text-[#8b95ad] mb-2">
                    <span className="px-2 py-0.5 rounded bg-[#07080a] text-[#00ff66] border border-[#00ff66]/30 font-bold">
                      {item.tag}
                    </span>
                    <span>{item.date}</span>
                  </div>
                  <h4 className="text-white font-bold text-sm leading-snug hover:text-[#00f0ff] transition-colors">
                    {item.title}
                  </h4>
                  <p className="text-xs text-[#8b95ad] mt-2 leading-relaxed font-sans">
                    {item.summary}
                  </p>
                </div>

                {item.link && (
                  <div className="mt-4 pt-2 border-t border-[#1e2436] text-[11px]">
                    <a
                      href={item.link}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="inline-flex items-center gap-1.5 text-[#00f0ff] hover:underline font-bold"
                    >
                      <span>{t.liveUpdates.viewPost}</span>
                      <ExternalLink className="w-3 h-3" />
                    </a>
                  </div>
                )}
              </div>
            ))}
          </div>

        </div>

      </div>
    </section>
  );
};
